preset: symfony

risky: false

enabled:
  - align_double_arrow
  - concat_with_spaces
  - ordered_class_elements
  - ordered_imports

disabled:
  - concat_without_spaces
  - no_extra_block_blank_lines
  - phpdoc_to_comment
  - unalign_double_arrow
